Exception on /events/Favorite [GET]
Traceback (most recent call last):
  File "/home/z/SMART_WeChatMiniProgram/venv/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/z/SMART_WeChatMiniProgram/venv/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/z/SMART_WeChatMiniProgram/venv/lib/python3.5/site-packages/flask_restful/__init__.py", line 480, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/z/SMART_WeChatMiniProgram/venv/lib/python3.5/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/z/SMART_WeChatMiniProgram/venv/lib/python3.5/site-packages/flask_restful/__init__.py", line 595, in dispatch_request
    resp = meth(*args, **kwargs)
  File "testApp.py", line 32, in get
    return databaseOperations.getUserFavoriteEvents(userID)
  File "/home/z/SMART_WeChatMiniProgram/utils/databaseOperations.py", line 24, in getUserFavoriteEvents
    """) % (userID)
sqlite3.OperationalError: near "%": syntax error
Exception on /events/Favorite [GET]
Traceback (most recent call last):
  File "/home/z/SMART_WeChatMiniProgram/venv/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/z/SMART_WeChatMiniProgram/venv/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/z/SMART_WeChatMiniProgram/venv/lib/python3.5/site-packages/flask_restful/__init__.py", line 480, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/z/SMART_WeChatMiniProgram/venv/lib/python3.5/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/z/SMART_WeChatMiniProgram/venv/lib/python3.5/site-packages/flask_restful/__init__.py", line 595, in dispatch_request
    resp = meth(*args, **kwargs)
  File "testApp.py", line 32, in get
    return databaseOperations.getUserFavoriteEvents(userID)
  File "/home/z/SMART_WeChatMiniProgram/utils/databaseOperations.py", line 24, in getUserFavoriteEvents
    """) % (userID)
sqlite3.OperationalError: near "%": syntax error
Exception on /events/Favorite [GET]
Traceback (most recent call last):
  File "/home/z/SMART_WeChatMiniProgram/venv/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/z/SMART_WeChatMiniProgram/venv/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/z/SMART_WeChatMiniProgram/venv/lib/python3.5/site-packages/flask_restful/__init__.py", line 480, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/z/SMART_WeChatMiniProgram/venv/lib/python3.5/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/z/SMART_WeChatMiniProgram/venv/lib/python3.5/site-packages/flask_restful/__init__.py", line 595, in dispatch_request
    resp = meth(*args, **kwargs)
  File "testApp.py", line 32, in get
    return databaseOperations.getUserFavoriteEvents(userID)
  File "/home/z/SMART_WeChatMiniProgram/utils/databaseOperations.py", line 25, in getUserFavoriteEvents
    """) % (userID)
sqlite3.OperationalError: near "%": syntax error
Exception on /events/Favorite [GET]
Traceback (most recent call last):
  File "/home/z/SMART_WeChatMiniProgram/venv/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/z/SMART_WeChatMiniProgram/venv/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/z/SMART_WeChatMiniProgram/venv/lib/python3.5/site-packages/flask_restful/__init__.py", line 480, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/z/SMART_WeChatMiniProgram/venv/lib/python3.5/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/z/SMART_WeChatMiniProgram/venv/lib/python3.5/site-packages/flask_restful/__init__.py", line 595, in dispatch_request
    resp = meth(*args, **kwargs)
  File "testApp.py", line 32, in get
    return databaseOperations.getUserFavoriteEvents(userID)
  File "/home/z/SMART_WeChatMiniProgram/utils/databaseOperations.py", line 25, in getUserFavoriteEvents
    cursor.execute(query)
sqlite3.OperationalError: no such column: zhangyifeng
Exception on /events/Favorite [GET]
Traceback (most recent call last):
  File "/home/z/SMART_WeChatMiniProgram/venv/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/z/SMART_WeChatMiniProgram/venv/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/z/SMART_WeChatMiniProgram/venv/lib/python3.5/site-packages/flask_restful/__init__.py", line 480, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/z/SMART_WeChatMiniProgram/venv/lib/python3.5/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/z/SMART_WeChatMiniProgram/venv/lib/python3.5/site-packages/flask_restful/__init__.py", line 595, in dispatch_request
    resp = meth(*args, **kwargs)
  File "testApp.py", line 32, in get
    return databaseOperations.getUserFavoriteEvents(userID)
  File "/home/z/SMART_WeChatMiniProgram/utils/databaseOperations.py", line 26, in getUserFavoriteEvents
    cursor.execute(query)
sqlite3.OperationalError: no such column: zhangyifeng
Exception on /events/Popular [GET]
Traceback (most recent call last):
  File "/home/z/SMART_WeChatMiniProgram/venv/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/z/SMART_WeChatMiniProgram/venv/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/z/SMART_WeChatMiniProgram/venv/lib/python3.5/site-packages/flask_restful/__init__.py", line 480, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/z/SMART_WeChatMiniProgram/venv/lib/python3.5/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/z/SMART_WeChatMiniProgram/venv/lib/python3.5/site-packages/flask_restful/__init__.py", line 595, in dispatch_request
    resp = meth(*args, **kwargs)
  File "testApp.py", line 31, in get
    return databaseOperations.getPopularEvents()
  File "/home/z/SMART_WeChatMiniProgram/utils/databaseOperations.py", line 24, in getPopularEvents
    cursor.execute(query)
NameError: name 'cursor' is not defined
Exception on /events/Popular [GET]
Traceback (most recent call last):
  File "/home/z/SMART_WeChatMiniProgram/venv/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/z/SMART_WeChatMiniProgram/venv/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/z/SMART_WeChatMiniProgram/venv/lib/python3.5/site-packages/flask_restful/__init__.py", line 480, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/z/SMART_WeChatMiniProgram/venv/lib/python3.5/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/z/SMART_WeChatMiniProgram/venv/lib/python3.5/site-packages/flask_restful/__init__.py", line 595, in dispatch_request
    resp = meth(*args, **kwargs)
  File "testApp.py", line 31, in get
    return databaseOperations.getPopularEvents()
  File "/home/z/SMART_WeChatMiniProgram/utils/databaseOperations.py", line 24, in getPopularEvents
    cursor.execute(query)
sqlite3.OperationalError: no such column: count
Exception on /events/Popular [GET]
Traceback (most recent call last):
  File "/home/z/SMART_WeChatMiniProgram/venv/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/z/SMART_WeChatMiniProgram/venv/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/z/SMART_WeChatMiniProgram/venv/lib/python3.5/site-packages/flask_restful/__init__.py", line 480, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/z/SMART_WeChatMiniProgram/venv/lib/python3.5/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/z/SMART_WeChatMiniProgram/venv/lib/python3.5/site-packages/flask_restful/__init__.py", line 595, in dispatch_request
    resp = meth(*args, **kwargs)
  File "testApp.py", line 31, in get
    return databaseOperations.getPopularEvents()
  File "/home/z/SMART_WeChatMiniProgram/utils/databaseOperations.py", line 25, in getPopularEvents
    cursor.execute(query)
sqlite3.OperationalError: no such column: count
